### ISSUE TITLE
Add MarkDuplicates to GATK DNA pipeline

### ISSUE THREAD

**Issue by j23414** [isugifNF/GATK#14]
## Description:

Add MarkDuplicates to the DNA pipeline as well based on pipeline diagrammed from Broad Institute at:

* https://github.com/broadinstitute/gatk-docs/blob/master/gatk3-methods-and-algorithms/Best_Practices_for_Variant_Discovery_in_DNAseq.md

## Potential Solutions

* https://github.com/HuffordLab/Maize_WGS_Build/commit/247ed97db8622717cd045fcd328b61115d87f28d

**Comment by j23414** [comment]
Clarification question for @aseetharam and @vsatheesh. Referring to a specific line in the Bioinformatics Workbook ([gatk-dnaseq-best-practices-workflow.md](https://github.com/ISUgenomics/bioinformatics-workbook/blob/27c297d5892c5bbcfea484dd0bccf662848dba48/dataAnalysis/VariantCalling/gatk-dnaseq-best-practices-workflow.md?plain=1#L492-L499)), it seems that we are running the MarkDuplicates for DNAseq analysis with certain parameters, as outlined in the given Bash script.

```bash
gatk --java-options ${JAVA_OPTIONS} MarkDuplicates \
  --INPUT ${OUT}_snippet_mergebamalignment.bam \
  --OUTPUT ${OUT}_prefinal.bam \
  --METRICS_FILE ${OUT}_mergebamalignment_markduplicates_metrics.txt \
  --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500 \
  --CREATE_INDEX true \
  --TMP_DIR $TMPDIR || {
echo >&2 ERROR: MarkDuplicates failed for $OUT
```

The parameters nearly, but do not entirely match the suggestion for [gatk-workflows/gatk4-data-processing/processing-for-variant-discovery-gatk4.wdl#L477-L486](https://github.com/gatk-workflows/gatk4-data-processing/blob/master/processing-for-variant-discovery-gatk4.wdl#L477-L486)

```bash
 ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms~{command_mem_gb}G" \
      MarkDuplicates \
      --INPUT ~{sep=' --INPUT ' input_bams} \
      --OUTPUT ~{output_bam_basename}.bam \
      --METRICS_FILE ~{metrics_filename} \
      --VALIDATION_STRINGENCY SILENT \
      --OPTICAL_DUPLICATE_PIXEL_DISTANCE 2500 \
      --ASSUME_SORT_ORDER "queryname" \
      --CREATE_MD5_FILE true
```

And does not match (perhaps as expected) the RNAseq's MarkDuplicates [gatk-workflows/gatk4-rnaseq-germline-snps-indels/gatk4-rna-best-practices.wdl#L470-L476](https://github.com/gatk-workflows/gatk4-rnaseq-germline-snps-indels/blob/c5fc93ea0424c7eaa3dd6bb0e50ce8deb241c0d5/gatk4-rna-best-practices.wdl#L470-L476)

```bash
${gatk_path} \
    MarkDuplicates \
    --INPUT ${input_bam} \
    --OUTPUT ${base_name}.bam  \
    --CREATE_INDEX true \
    --VALIDATION_STRINGENCY SILENT \
    --METRICS_FILE ${base_name}.metrics
```

My question for @aseetharam and @vsatheesh is what set of parameters would be reasonable for the DNAseq pipeline?

I'm not running this pipeline regularly on plant species so I hesitate to just guess. Could someone write up the rational of the parameter choices here for clarification?

**Comment by aseetharam** [comment]
The variation I've observed in the DNAseq doesn't have any significant impact.

Distinct to our approach are:

```plaintext
--CREATE_INDEX true # creates a bam output index file (`.bai`)
--TMP_DIR $TMPDIR # utilizes a temporary directory instead of the default /tmp, aligning with our cluster setup (although note that this is no longer necessary, as /tmp now defaults to $TMPDIR)
```

Distinct to their method:

```plaintext
--ASSUME_SORT_ORDER "queryname" # organizes based on query name rather than the default coordinate sort order
--CREATE_MD5_FILE true # generates a hash value for file comparison
```

While these differences won't affect the final outcome, considering our commitment to adhering to best practices, it might be preferable to maintain consistency, as suggested by @j23414 

Yes, RNAseq does not need the optical distance parameter. The objective of RNAseq is to get counts of the same mRNA, unlike the DNAseq.

**Comment by aseetharam** [comment]
oh, if we are using the `queryname` sort order, we will have to do the `samtools` sorting the same way before this step.

**Comment by j23414** [comment]
By `samtools` sorting, you mean:

```bash
~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms~{command_mem_gb_sort}G" \
      SortSam \
      --INPUT ~{input_bam} \
      --OUTPUT /dev/stdout \
      --SORT_ORDER "coordinate" \
      --CREATE_INDEX false \
      --CREATE_MD5_FILE false \
    | \
    ~{gatk_path} --java-options "-Dsamjdk.compression_level=~{compression_level} -Xms~{command_mem_gb_fix}G" \
      SetNmMdAndUqTags \
      --INPUT /dev/stdin \
      --OUTPUT ~{output_bam_basename}.bam \
      --CREATE_INDEX true \
      --CREATE_MD5_FILE true \
      --REFERENCE_SEQUENCE ~{ref_fasta}
 ```
 
 Sure, I can add it to the [modules/DNAseq.nf](https://github.com/isugifNF/GATK-flow/blob/5a26fc9edcb64ef153af9feac5ff4b442e855ca4/modules/local/DNAseq.nf#L129).

**Comment by aseetharam** [comment]
yes! that's it!

**Comment by j23414** [comment]
Thanks for taking a look! I made an attempt in the following two commits. Let me know if anything looks off:

* Added SortAndFixTags 5463d6248137a827c60af6ad5a707176dc533762
* Added MarkDuplicates 7c14f1a216de7cfce91e3be3c404afaf9c91bc6f

**Comment by vsatheesh** [comment]
I just noticed that SortAndFixTags should go after MarkDuplicates based on the [GATK wdl](https://github.com/gatk-workflows/gatk4-data-processing/blob/c44603c464fe3cb7d9b82da2a95f844fdeb20e3c/processing-for-variant-discovery-gatk4.wdl#L157).

**Comment by j23414** [comment]
Rebased and hopefully fixed, see https://github.com/isugifNF/GATK-flow/pull/15#issuecomment-1924922674
